# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 https://nicoyepes.github.io
baseurl:             'learning_journal/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nico Yepes
  url:               swellventurepartners.com
  email:             nico@swellventurepartners.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
